server:
  port: 0
  servlet:
    context-path: /api/v1/accommodation-management

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  api-docs:
    path: /swagger.v1+json

spring:
  application:
    name: accommodation-management
    version: v1
  datasource:
    url: jdbc:mysql://localhost:3306/accommodation
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: rabbitmq

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

request-mapping:
  controller:
    department: department
    city: city
    destination: destination
    accommodation: accommodation
