server:
  port: 2208

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: accommodation-management
          uri: lb://accommodation-management
          predicates:
            - Path=/api/v1/accommodation-management/**
        - id: reservation-management
          uri: lb://reservation-management
          predicates:
            - Path=/api/v1/reservation-management/**
        - id: user-management
          uri: lb://user-management
          predicates:
            - Path=/api/v1/user-management/**
        - id: authentication-management
          uri: lb://authentication-management
          predicates:
            - Path=/api/v1/authentication-management/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/travel-agency
          jwk-set-uri: http://localhost:9090/realms/travel-agency/protocol/openid-connect/certs
    output:
      ansi:
        enabled: always

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-client
      principal-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/