server:
  port: 2208

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: accommodation-management
          uri: lb://accommodation-management
          predicates:
            - Path=/api/v1/accommodation-management/**
        - id: reservation-management
          uri: lb://reservation-management
          predicates:
            - Path=/api/v1/reservation-management/**
        - id: user-management
          uri: lb://user-management
          predicates:
            - Path=/api/v1/user-management/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/